### YAML Template.
#---
# server
server:
  port: 8080
# spring
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/master_db?createDatabaseIfNotExist=true&useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Manila
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

      hikari:
        max-lifetime: 1800000
        minimum-idle: 1
        maximum-pool-size: 10
        connection-timeout: 3000
        pool-name: myConnPool
        leak-detection-threshold: 45000
        register-mbeans: true
        auto-commit: true